require:
  - rubocop-i18n
  - rubocop-md
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rails/ContentTag:
  Enabled: false

Markdown:
  Autodetect: true

I18n/GetText:
  Enabled: true
I18n/RailsI18n:
  Enabled: false
